Repository TeamCatchMe/CatchMe-If-You-iOS, pull requests merged in 2021-07, with the labels that each got.

#19 Feature/8 character layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/Cells/Character/CharacterReportTVC.swift
  CatchMe/CatchMe/Source/Cells/Character/CharacterTVC.swift
  CatchMe/CatchMe/Source/Components/Character/CharacterHeaderView.swift
  CatchMe/CatchMe/Source/Components/Character/CharacterUpperView.swift
  CatchMe/CatchMe/Source/Components/Character/NavigationBar.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
  CatchMe/Podfile.lock
Labels: P0, heerucan✨, review required🍎

#20 Feature/9 main layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Resource/Xibs/Main/characterCVC.xib
  CatchMe/CatchMe/Source/Cells/Main/characterCVC.swift
  CatchMe/CatchMe/Source/Components/Main/PageControl.swift
  CatchMe/CatchMe/Source/Components/Main/mainReportView.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
Labels: P0, review required🍎, yangsubinn🐣

#22 Feature/21 character layout
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Source/Cells/Character/CharacterReportTVC.swift
  CatchMe/CatchMe/Source/Cells/Character/CharacterTVC.swift
  CatchMe/CatchMe/Source/Components/Character/CharacterHeaderView.swift
  CatchMe/CatchMe/Source/Components/Character/CharacterUpperView.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
Labels: P0, heerucan✨, review required🍎

#23 Feature/11 main feature
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
Labels: P0, review required🍎, yangsubinn🐣

#25 Feature/6 report layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Source/Cells/Report/CalendarCVC.swift
  CatchMe/CatchMe/Source/Components/Report/CalendarTitleView.swift
  CatchMe/CatchMe/Source/Components/Report/CharacterView.swift
  CatchMe/CatchMe/Source/Components/Report/ReportView.swift
  CatchMe/CatchMe/Source/Components/Report/TitleView.swift
  CatchMe/CatchMe/Source/ViewControllers/ReportVC.swift
  CatchMe/Podfile.lock
Labels: P0, YoonAh-dev🧚🏻‍♂️, review required🍎

#28 Feature/12 calendar popup
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Report.storyboard
  CatchMe/CatchMe/Source/Cells/Report/CalendarCVC.swift
  CatchMe/CatchMe/Source/Cells/Report/CatchuCVC.swift
  CatchMe/CatchMe/Source/Components/Report/CharacterView.swift
  CatchMe/CatchMe/Source/Components/Report/PopupView.swift
  CatchMe/CatchMe/Source/Components/Report/ReportView.swift
  CatchMe/CatchMe/Source/ViewControllers/ReportPopupVC.swift
  CatchMe/CatchMe/Source/ViewControllers/ReportVC.swift
Labels: P0, YoonAh-dev🧚🏻‍♂️, review required🍎

#31 Feature/30 modify report layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
  CatchMe/CatchMe/Source/Components/Report/ReportView.swift
  CatchMe/CatchMe/Source/Extensions/UIColor+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/AddCatchuVC.swift
  CatchMe/CatchMe/Source/ViewControllers/ReportPopupVC.swift
  CatchMe/CatchMe/Source/ViewControllers/ReportVC.swift
Labels: YoonAh-dev🧚🏻‍♂️

#33 Feature/24 main card view layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Resource/Xibs/Main/CharacterCVC.xib
  CatchMe/CatchMe/Resource/Xibs/MainCard/MainCardCVC.xib
  CatchMe/CatchMe/Source/Cells/Main/CharacterCVC.swift
  CatchMe/CatchMe/Source/Cells/MainCard/MainCardCVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/Podfile.lock
Labels: P0, yangsubinn🐣

#41 Feature/37 setting view layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Setting.storyboard
  CatchMe/CatchMe/Resource/Xibs/Setting/SettingTVC.xib
  CatchMe/CatchMe/Source/Cells/Setting/SettingTVC.swift
  CatchMe/CatchMe/Source/ViewControllers/SettingVC.swift
Labels: review required🍎, yangsubinn🐣

#43 Feature/14 add catchu layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Source/Cells/AddCatchu/CarouselCVC.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/AddCatchuPageControl.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/CatchuTitleView.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/FirstFlowView.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/SecondFlowView.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/ThirdFlowView.swift
  CatchMe/CatchMe/Source/Components/Shared/BackButton.swift
  CatchMe/CatchMe/Source/Components/Shared/BottomButton.swift
  CatchMe/CatchMe/Source/Components/Shared/CustomTextField.swift
  CatchMe/CatchMe/Source/Extensions/UIView+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/AddCatchuVC.swift
  CatchMe/CatchMe/Source/ViewControllers/ReportPopupVC.swift
  CatchMe/Podfile.lock
Labels: P0, YoonAh-dev🧚🏻‍♂️, review required🍎

#51 Feature/49 character layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Source/Components/Character/CharacterFooterView.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
Labels: P0, heerucan🚀, review required🍎

#55 Feature/44 login layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Login.storyboard
  CatchMe/CatchMe/Source/Components/AddCatchu/SecondFlowView.swift
  CatchMe/CatchMe/Source/Components/Login/TextFieldView.swift
  CatchMe/CatchMe/Source/Components/Shared/CustomTextField.swift
  CatchMe/CatchMe/Source/Extensions/UIButton+Extension.swift
  CatchMe/CatchMe/Source/Extensions/UIColor+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/LoginVC.swift
  CatchMe/Podfile.lock
Labels: P2, YoonAh-dev🌈, review required🍎

#57 Feature/54 login
  CatchMe/CatchMe/Source/Components/Login/TextFieldView.swift
  CatchMe/CatchMe/Source/Components/Shared/CustomTextField.swift
  CatchMe/CatchMe/Source/Extensions/UIView+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/LoginVC.swift
Labels: P2, YoonAh-dev🌈, review required🍎

#56 Feature/34 main view layout fix
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/Components/Main/mainReportView.swift
  CatchMe/CatchMe/Source/Extensions/UILabel+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/Podfile.lock
Labels: P0, review required🍎, yangsubinn🐣

#59 Feature/36 main card view layout fix
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/Cells/MainCard/MainCardCVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
Labels: P0, review required🍎, yangsubinn🐣

#60 Feature/48 character feature
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Source/Cells/Character/CharacterFirstTVC.swift
  CatchMe/CatchMe/Source/Cells/Character/CharacterTVC.swift
  CatchMe/CatchMe/Source/Components/Character/CharacterHeaderView.swift
  CatchMe/CatchMe/Source/Components/Character/MoreMenuView.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
Labels: P0, heerucan🚀, review required🍎

#63 Feature/46 signup layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Storyboards/Login.storyboard
  CatchMe/CatchMe/Source/Components/AddCatchu/SecondFlowView.swift
  CatchMe/CatchMe/Source/Components/Login/SignupNaviBar.swift
  CatchMe/CatchMe/Source/Components/Login/SignupTextFieldView.swift
  CatchMe/CatchMe/Source/Components/Login/TextFieldView.swift
  CatchMe/CatchMe/Source/Components/Shared/CustomTextField.swift
  CatchMe/CatchMe/Source/Extensions/UIApplication+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/SignupVC.swift
  CatchMe/Podfile.lock
Labels: P2, YoonAh-dev🌈, review required🍎

#67 Feature/58 signup logic
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Source/Components/Login/SignupTextFieldView.swift
  CatchMe/CatchMe/Source/Components/Login/TextFieldView.swift
  CatchMe/CatchMe/Source/Extensions/String+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/SignupVC.swift
Labels: P2, YoonAh-dev🌈, review required🍎

#69 Feature/42 add action layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
  CatchMe/CatchMe/Source/Components/AddAction/AddActionPopupView.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionPopupVC.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
  CatchMe/Podfile.lock
Labels: P1, heerucan🏄‍♂️, review required🍎

#71 Feature/39 main view layout empty
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/Components/Main/mainReportView.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/Podfile.lock
Labels: P0, review required🍎, yangsubinn🐣

#73 Feature/64 add action feature
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
Labels: P1, heerucan🏄‍♂️, review required🍎

#76 Feature/70 main card view action sheet
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
  CatchMe/Podfile.lock
Labels: P0, review required🍎, yangsubinn🐣

#80 Feature/77 look view layout
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Resource/Xibs/Look/LookCVC.xib
  CatchMe/CatchMe/Source/Cells/Look/LookCVC.swift
  CatchMe/CatchMe/Source/ViewControllers/LookVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
  CatchMe/Podfile.lock
Labels: P1, review required🍎, yangsubinn🐣

#83 Feature/79 add catchu UI
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
  CatchMe/CatchMe/Source/Cells/AddCatchu/CarouselCVC.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/AddCatchuPageControl.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/CatchuTitleView.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/FirstFlowView.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/SecondFlowView.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/ThirdFlowView.swift
  CatchMe/CatchMe/Source/Components/Shared/BottomButton.swift
  CatchMe/CatchMe/Source/Components/Shared/CustomTextField.swift
  CatchMe/CatchMe/Source/Extensions/UILabel+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/AddCatchuVC.swift
  CatchMe/Podfile.lock
Labels: P0, YoonAh-dev🌈, review required🍎

#86 Feature/84 login UI
  CatchMe/CatchMe/Resource/Assets.xcassets/logo.imageset/Contents.json
  CatchMe/CatchMe/Resource/Assets.xcassets/logo.imageset/logo.png
  CatchMe/CatchMe/Resource/Assets.xcassets/logoImage.imageset/Contents.json
  CatchMe/CatchMe/Resource/Assets.xcassets/logoImage.imageset/logoImage.png
  CatchMe/CatchMe/Resource/Assets.xcassets/logoImage.imageset/logoImage@2x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/logoImage.imageset/logoImage@3x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/systemsLock2Fill.imageset/Contents.json
  CatchMe/CatchMe/Resource/Assets.xcassets/systemsLock2Fill.imageset/systemsLock2Fill.png
  CatchMe/CatchMe/Resource/Assets.xcassets/systemsLock2Fill.imageset/systemsLock2Fill@2x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/systemsLock2Fill.imageset/systemsLock2Fill@3x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/usersUser3Fill.imageset/Contents.json
  CatchMe/CatchMe/Resource/Assets.xcassets/usersUser3Fill.imageset/usersUser3Fill.png
  CatchMe/CatchMe/Resource/Assets.xcassets/usersUser3Fill.imageset/usersUser3Fill@2x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/usersUser3Fill.imageset/usersUser3Fill@3x.png
  CatchMe/CatchMe/Resource/Storyboards/Login.storyboard
  CatchMe/CatchMe/Source/Components/AddCatchu/FirstFlowView.swift
  CatchMe/CatchMe/Source/Components/Login/SignupNaviBar.swift
  CatchMe/CatchMe/Source/Components/Login/SignupTextFieldView.swift
  CatchMe/CatchMe/Source/Components/Login/TextFieldView.swift
  CatchMe/CatchMe/Source/Components/Shared/CustomTextField.swift
  CatchMe/CatchMe/Source/ViewControllers/LoginVC.swift
Labels: P2, YoonAh-dev🌈, review required🍎

#89 Feature/13 character animation
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
  CatchMe/Podfile.lock
Labels: P0, heerucan🏄‍♂️, review required🍎

#97 Feature/96 login service
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/GeneralAPI.swift
  CatchMe/CatchMe/Resource/APIServices/Login.swift
  CatchMe/CatchMe/Resource/APIServices/Services/LoginService.swift
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Login.storyboard
  CatchMe/CatchMe/Source/Components/Login/TextFieldView.swift
  CatchMe/CatchMe/Source/Models/Login/SigninModel.swift
  CatchMe/CatchMe/Source/Models/Login/SigninRequest.swift
  CatchMe/CatchMe/Source/Models/Login/SignupRequest.swift
  CatchMe/CatchMe/Source/ViewControllers/LoginVC.swift
  CatchMe/CatchMe/Source/ViewModels/LoginViewModel.swift
Labels: P2, YoonAh-dev🌈, review required🍎

#100 Feature/99 email check service
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/Services/LoginService.swift
  CatchMe/CatchMe/Source/Components/Login/SignupTextFieldView.swift
  CatchMe/CatchMe/Source/Models/Login/EmailCheckModel.swift
  CatchMe/CatchMe/Source/Models/Login/EmailCheckRequest.swift
  CatchMe/CatchMe/Source/ViewModels/LoginViewModel.swift
Labels: P2, YoonAh-dev🌈, review required🍎

#101 Feature/85 look UI
  CatchMe/CatchMe/Resource/Assets.xcassets/icLookMore.imageset/Contents.json
  CatchMe/CatchMe/Resource/Assets.xcassets/icLookMore.imageset/icLookMore.png
  CatchMe/CatchMe/Resource/Assets.xcassets/icLookMore.imageset/icLookMore@2x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/icLookMore.imageset/icLookMore@3x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/imgGroupCatchu.imageset/Contents.json
  CatchMe/CatchMe/Resource/Assets.xcassets/imgGroupCatchu.imageset/imgGroupCatchu.png
  CatchMe/CatchMe/Resource/Assets.xcassets/imgGroupCatchu.imageset/imgGroupCatchu@2x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/imgGroupCatchu.imageset/imgGroupCatchu@3x.png
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/Cells/Look/LookCVC.swift
  CatchMe/CatchMe/Source/ViewControllers/LookVC.swift
  CatchMe/Podfile.lock
Labels: P1, review required🍎, yangsubinn🐣

#102 Feature/98 signup service
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Source/Components/Login/SignupTextFieldView.swift
  CatchMe/CatchMe/Source/Components/Login/TextFieldView.swift
  CatchMe/CatchMe/Source/Models/Login/SignupModel.swift
  CatchMe/CatchMe/Source/Models/Login/SignupRequest.swift
  CatchMe/CatchMe/Source/ViewControllers/SignupVC.swift
  CatchMe/CatchMe/Source/ViewModels/LoginViewModel.swift
Labels: P2, YoonAh-dev🌈, review required🍎

#104 Feature/103 add catchu service
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/GeneralAPI.swift
  CatchMe/CatchMe/Resource/APIServices/Services/MainCardService.swift
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
  CatchMe/CatchMe/Source/Components/AddCatchu/FirstFlowView.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/SecondFlowView.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/ThirdFlowView.swift
  CatchMe/CatchMe/Source/Components/Report/PopupView.swift
  CatchMe/CatchMe/Source/Models/MainCard/CreateCharacterModel.swift
  CatchMe/CatchMe/Source/Models/MainCard/CreateCharacterRequest.swift
  CatchMe/CatchMe/Source/ViewControllers/AddCatchuVC.swift
  CatchMe/CatchMe/Source/ViewModels/MainCardViewModel.swift
  CatchMe/Podfile.lock
Labels: P0, YoonAh-dev🌈, review required🍎

#107 Feature/93 main view layout edit
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Resource/Xibs/Main/CharacterCVC.xib
  CatchMe/CatchMe/Source/Cells/Main/CharacterCVC.swift
  CatchMe/CatchMe/Source/Cells/MainCard/MainCardCVC.swift
  CatchMe/CatchMe/Source/Components/Main/mainReportView.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
Labels: P0, review required🍎, yangsubinn🐣

#109 Feature/62 add action feature
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
  CatchMe/CatchMe/Source/Components/AddAction/AddActionDatePickerPopupView.swift
  CatchMe/CatchMe/Source/Components/Character/CharacterHeaderView.swift
  CatchMe/CatchMe/Source/Extensions/UIColor+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionDatePickerPopupVC.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
  CatchMe/Podfile.lock
Labels: P1, heerucan🏄‍♂️, review required🍎

#106 Feature/105 catchu pop up
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
  CatchMe/CatchMe/Source/Components/AddCatchu/AddCatchuPopupView.swift
  CatchMe/CatchMe/Source/Components/Shared/XmarkButton.swift
  CatchMe/CatchMe/Source/Extensions/UILabel+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/AddCatchuPopupVC.swift
  CatchMe/CatchMe/Source/ViewControllers/AddCatchuVC.swift
Labels: P0, YoonAh-dev🌈, review required🍎

#112 Feature/108 main popup
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatchuCatching.imageset/Contents.json
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatchuCatching.imageset/btnCatchuCatching.png
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatchuCatching.imageset/btnCatchuCatching@2x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatchuCatching.imageset/btnCatchuCatching@3x.png
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/Cells/Main/CharacterCVC.swift
  CatchMe/CatchMe/Source/Components/Main/MainPopupView.swift
  CatchMe/CatchMe/Source/Components/Main/MainReportView.swift
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainPopupVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
Labels: P1, review required🍎, yangsubinn🐣

#115 Feature/61 add action feature
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
Labels: P1, heerucan🏄‍♂️, review required🍎

#116 Feature/15 character feature
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
Labels: P0, heerucan🏄‍♂️, review required🍎

#118 Feature/66 setting view layout add
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Fonts/DINPro-Bold.otf
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Resource/Storyboards/Setting.storyboard
  CatchMe/CatchMe/Source/ViewControllers/ChangePasswordView.swift
  CatchMe/CatchMe/Source/ViewControllers/CurrentPasswordView.swift
  CatchMe/CatchMe/Source/ViewControllers/EditNicknameVC.swift
  CatchMe/CatchMe/Source/ViewControllers/EditPasswordVC.swift
  CatchMe/CatchMe/Source/ViewControllers/LogoutPopupView.swift
  CatchMe/CatchMe/Source/ViewControllers/LogoutVC.swift
  CatchMe/CatchMe/Source/ViewControllers/SettingVC.swift
  CatchMe/CatchMe/Source/ViewControllers/WithdrawalVC.swift
  CatchMe/Podfile.lock
Labels: P3, YoonAh-dev🌈, review required🍎, yangsubinn🐣

#120 Feature/113 main service
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/Services/MainService.swift
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatchuCatching.imageset/Contents.json
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatchuCatching.imageset/btnCatchuCatching.png
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatchuCatching.imageset/btnCatchuCatching@2x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatchuCatching.imageset/btnCatchuCatching@3x.png
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/Cells/Main/CharacterCVC.swift
  CatchMe/CatchMe/Source/Components/Main/MainReportView.swift
  CatchMe/CatchMe/Source/Extensions/Character+Extension.swift
  CatchMe/CatchMe/Source/Extensions/UIView+Extension.swift
  CatchMe/CatchMe/Source/Extensions/UIViewController+Extension.swift
  CatchMe/CatchMe/Source/Models/Main/MainModel.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/Podfile.lock
Labels: P0, yangsubinn🐣

#123 [Chore] Main 뷰 empty state 서버 연결 (#122)
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
Labels: P0, review required🍎, yangsubinn🐣

#129 Feature/121 main card service
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/Services/MainCardService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/MainService.swift
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/Cells/MainCard/MainCardCVC.swift
  CatchMe/CatchMe/Source/Models/MainCard/MainCardModel.swift
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
Labels: P0, review required🍎, yangsubinn🐣

#127 Feature/117 character service
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/Services/AddActionService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/CharacterService.swift
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Source/Cells/Character/CharacterFirstTVC.swift
  CatchMe/CatchMe/Source/Cells/Character/CharacterReportTVC.swift
  CatchMe/CatchMe/Source/Cells/Character/CharacterTVC.swift
  CatchMe/CatchMe/Source/Components/Character/CharacterHeaderView.swift
  CatchMe/CatchMe/Source/Components/Character/CharacterUpperView.swift
  CatchMe/CatchMe/Source/Models/Character/AddActionRequest.swift
  CatchMe/CatchMe/Source/Models/Character/CharacterModel.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
  CatchMe/CatchMe/Source/ViewModels/AddActionViewModel.swift
Labels: P0, heerucan🏄‍♂️

#133 Feature/130 main lottie
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/Services/LookService.swift
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Lottie/background_ios_375812.json
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/Models/Look/LookModel.swift
  CatchMe/CatchMe/Source/ViewControllers/LookVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/Podfile.lock
Labels: P0, review required🍎, yangsubinn🐣

#132 Feature/131 edit server
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/Services/CharacterService.swift
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
  CatchMe/CatchMe/Source/Models/Character/EditCharacterModel.swift
  CatchMe/CatchMe/Source/Models/Character/EditCharacterRequest.swift
  CatchMe/CatchMe/Source/ViewControllers/EditCatchuVC.swift
  CatchMe/CatchMe/Source/ViewModels/AddActionViewModel.swift
  CatchMe/CatchMe/Source/ViewModels/CharacterViewModel.swift
Labels: P1, YoonAh-dev🌈, review required🍎

#134 Feature/126 setting service
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/Login.swift
  CatchMe/CatchMe/Resource/APIServices/Services/SettingService.swift
  CatchMe/CatchMe/Source/Models/Login/SigninModel.swift
  CatchMe/CatchMe/Source/Models/Setting/NicknameRequest.swift
  CatchMe/CatchMe/Source/Models/Setting/PasswordCheckModel.swift
  CatchMe/CatchMe/Source/Models/Setting/PasswordRequest.swift
  CatchMe/CatchMe/Source/Models/Setting/SettingModel.swift
  CatchMe/CatchMe/Source/ViewControllers/EditNicknameVC.swift
  CatchMe/CatchMe/Source/ViewControllers/EditPasswordVC.swift
  CatchMe/CatchMe/Source/ViewControllers/WithdrawalVC.swift
  CatchMe/CatchMe/Source/ViewModels/LoginViewModel.swift
  CatchMe/CatchMe/Source/ViewModels/SettingViewModel.swift
  CatchMe/Podfile.lock
Labels: P3, YoonAh-dev🌈, review required🍎

#138 Feature/137 back color
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Resource/Storyboards/Report.storyboard
  CatchMe/CatchMe/Source/Cells/MainCard/MainCardCVC.swift
  CatchMe/CatchMe/Source/Extensions/UIColor+Extension.swift
  CatchMe/CatchMe/Source/Extensions/UIViewController+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/LookVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
Labels: review required🍎, yangsubinn🐣

#140 Feature/128 add action service
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/Services/APIConstants.swift
  CatchMe/CatchMe/Resource/APIServices/Services/AddActionDeleteService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/AddActionEditService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/AddActionNewService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/AddActionService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/NetworkResult.swift
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
  CatchMe/CatchMe/Source/Cells/Character/CharacterFirstTVC.swift
  CatchMe/CatchMe/Source/Cells/Character/CharacterTVC.swift
  CatchMe/CatchMe/Source/Models/AddAction/AddActionModel.swift
  CatchMe/CatchMe/Source/Models/AddAction/DeleteRequest.swift
  CatchMe/CatchMe/Source/Models/AddAction/EditRequest.swift
  CatchMe/CatchMe/Source/Models/AddAction/NewRequest.swift
  CatchMe/CatchMe/Source/Models/Character/Activity.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionDatePickerPopupVC.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
Labels: P1, heerucan🏄‍♂️

#143 Feature/135 ux color
  CatchMe/CatchMe/Resource/Storyboards/Character.storyboard
  CatchMe/CatchMe/Source/Cells/Report/CatchuCVC.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/FirstFlowView.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/SecondFlowView.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/ThirdFlowView.swift
  CatchMe/CatchMe/Source/Components/Login/SignupTextFieldView.swift
  CatchMe/CatchMe/Source/Components/Report/PopupView.swift
  CatchMe/CatchMe/Source/Components/Report/ReportView.swift
  CatchMe/CatchMe/Source/Components/Report/TitleView.swift
  CatchMe/CatchMe/Source/Components/Shared/CustomTextField.swift
  CatchMe/CatchMe/Source/Extensions/UIView+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/EditCatchuVC.swift
  CatchMe/CatchMe/Source/ViewControllers/ReportVC.swift
  CatchMe/Podfile.lock
Labels: YoonAh-dev🌈, review required🍎

#144 Feature/139 main report view fix
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Lottie/splash.json
  CatchMe/CatchMe/Resource/Storyboards/Login.storyboard
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/Components/Main/MainReportView.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/CatchMe/Source/ViewControllers/SplashVC.swift
  CatchMe/Podfile.lock
Labels: P0, review required🍎, yangsubinn🐣

#148 Feature/145 flow
  CatchMe/CatchMe/Resource/APIServices/Services/CharacterService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/MainCardService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/MainService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/ReportService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/SettingService.swift
  CatchMe/CatchMe/Resource/Storyboards/Main.storyboard
  CatchMe/CatchMe/Source/Components/AddCatchu/AddCatchuPopupView.swift
  CatchMe/CatchMe/Source/Components/AddCatchu/FirstFlowView.swift
  CatchMe/CatchMe/Source/Components/Character/NavigationBar.swift
  CatchMe/CatchMe/Source/Components/Login/TextFieldView.swift
  CatchMe/CatchMe/Source/Components/Main/MainReportView.swift
  CatchMe/CatchMe/Source/Components/Report/ReportView.swift
  CatchMe/CatchMe/Source/ViewControllers/AddCatchuVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
  CatchMe/CatchMe/Source/ViewControllers/EditNicknameVC.swift
  CatchMe/CatchMe/Source/ViewControllers/LogoutPopupView.swift
  CatchMe/CatchMe/Source/ViewControllers/LookVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/CatchMe/Source/ViewControllers/SplashVC.swift
  CatchMe/Podfile.lock
Labels: YoonAh-dev🌈, review required🍎

#150 Feature/146 main detail fix
  CatchMe/CatchMe/Source/Cells/Look/LookCVC.swift
  CatchMe/CatchMe/Source/ViewControllers/LookVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/Podfile.lock
Labels: P0, review required🍎, yangsubinn🐣

#151 Hotfix/149 reload
  CatchMe/CatchMe/Resource/APIServices/Login.swift
  CatchMe/CatchMe/Source/Components/Login/TextFieldView.swift
  CatchMe/CatchMe/Source/Components/Report/PopupView.swift
  CatchMe/CatchMe/Source/Extensions/UIView+Extension.swift
  CatchMe/CatchMe/Source/Extensions/UIViewController+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/AddCatchuVC.swift
  CatchMe/CatchMe/Source/ViewControllers/EditCatchuVC.swift
  CatchMe/CatchMe/Source/ViewControllers/LogoutPopupView.swift
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/CatchMe/Source/ViewControllers/SplashVC.swift
  CatchMe/CatchMe/Source/ViewModels/LoginViewModel.swift
  CatchMe/Podfile.lock
Labels: YoonAh-dev🌈, hotfix🔫, review required🍎

#152 Feature/141 edit action service
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/Services/CharacterService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/LookService.swift
  CatchMe/CatchMe/Resource/Assets.xcassets/imgScrollRadius.imageset/Contents.json
  CatchMe/CatchMe/Resource/Assets.xcassets/imgScrollRadius.imageset/imgScrollRadius.png
  CatchMe/CatchMe/Resource/Assets.xcassets/imgScrollRadius.imageset/imgScrollRadius@2x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/imgScrollRadius.imageset/imgScrollRadius@3x.png
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Source/Cells/Character/CharacterFirstTVC.swift
  CatchMe/CatchMe/Source/Cells/Character/CharacterTVC.swift
  CatchMe/CatchMe/Source/Components/Character/CharacterPopupView.swift
  CatchMe/CatchMe/Source/Models/Character/CharacterModel.swift
  CatchMe/CatchMe/Source/Models/Look/LookDetailModel.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionPopupVC.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterPopupVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
  CatchMe/Podfile.lock
Labels: P1, heerucan🏄‍♂️, review required🍎

#154 Feature/153 finalflow
  CatchMe/CatchMe/Resource/APIServices/Services/AddActionDeleteService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/AddActionEditService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/AddActionNewService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/CharacterService.swift
  CatchMe/CatchMe/Resource/APIServices/Services/LookService.swift
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Source/Cells/Main/CharacterCVC.swift
  CatchMe/CatchMe/Source/Components/Character/CharacterFooterView.swift
  CatchMe/CatchMe/Source/Components/Character/NavigationBar.swift
  CatchMe/CatchMe/Source/Models/Character/CharacterModel.swift
  CatchMe/CatchMe/Source/Models/Look/LookDetailModel.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
  CatchMe/CatchMe/Source/ViewControllers/EditCatchuVC.swift
  CatchMe/CatchMe/Source/ViewControllers/LookVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/Podfile.lock
Labels: P0, YoonAh-dev🌈, heerucan🏄‍♂️, yangsubinn🐣

#156 HOTFIX/65 almost final
  CatchMe/CatchMe/Source/Cells/Look/LookCVC.swift
  CatchMe/CatchMe/Source/Cells/MainCard/MainCardCVC.swift
  CatchMe/CatchMe/Source/ViewControllers/LookVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/Podfile.lock
Labels: P0, yangsubinn🐣

#158 Hotfix/155 root
  CatchMe/CatchMe.xcodeproj/project.pbxproj
  CatchMe/CatchMe/Resource/APIServices/Login.swift
  CatchMe/CatchMe/Resource/Info.plist
  CatchMe/CatchMe/Resource/Storyboards/Login.storyboard
  CatchMe/CatchMe/Resource/Storyboards/Splash.storyboard
  CatchMe/CatchMe/Source/Components/Login/SignupTextFieldView.swift
  CatchMe/CatchMe/Source/Extensions/UIImage+Extension.swift
  CatchMe/CatchMe/Source/Extensions/UIWindow+Extension.swift
  CatchMe/CatchMe/Source/ViewControllers/LogoutPopupView.swift
  CatchMe/Podfile.lock
Labels: YoonAh-dev🌈, hotfix🔫

#160 Hotfix/157 main card align
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatching.imageset/Contents.json
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatching.imageset/btnCatching.png
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatching.imageset/btnCatching@2x.png
  CatchMe/CatchMe/Resource/Assets.xcassets/btnCatching.imageset/btnCatching@3x.png
  CatchMe/CatchMe/Source/Cells/Character/CharacterFirstTVC.swift
  CatchMe/CatchMe/Source/Cells/Character/CharacterTVC.swift
  CatchMe/CatchMe/Source/Models/Character/CharacterModel.swift
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
  CatchMe/Podfile.lock
Labels: hotfix🔫, yangsubinn🐣

#162 [Fix] Main 뷰 활동리포트 문제 해결(#161)
  CatchMe/CatchMe/Source/Components/Main/MainReportView.swift
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
Labels: hotfix🔫, yangsubinn🐣

#163 Feature/147 look detail service
  CatchMe/CatchMe/Source/Cells/Character/CharacterFirstTVC.swift
  CatchMe/CatchMe/Source/Components/AddAction/AddActionDatePickerPopupView.swift
  CatchMe/CatchMe/Source/Components/Character/CharacterHeaderView.swift
  CatchMe/CatchMe/Source/Components/Character/NavigationBar.swift
  CatchMe/CatchMe/Source/Models/Look/LookDetailModel.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionDatePickerPopupVC.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
  CatchMe/CatchMe/Source/ViewControllers/EditCatchuVC.swift
  CatchMe/CatchMe/Source/ViewControllers/LookVC.swift
Labels: P1, heerucan🏄‍♂️, review required🍎

#167 Hotfix/164 look detail
  CatchMe/CatchMe/Source/Cells/Character/CharacterFirstTVC.swift
  CatchMe/CatchMe/Source/Cells/Character/CharacterTVC.swift
  CatchMe/CatchMe/Source/Components/AddAction/AddActionDatePickerPopupView.swift
  CatchMe/CatchMe/Source/ViewControllers/AddActionVC.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
  CatchMe/Podfile.lock
Labels: heerucan🏄‍♂️, review required🍎

#169 Hotfix/166 UI
  CatchMe/CatchMe/Resource/Storyboards/Report.storyboard
  CatchMe/CatchMe/Source/Components/Character/NavigationBar.swift
  CatchMe/CatchMe/Source/Components/Report/PopupView.swift
  CatchMe/CatchMe/Source/Components/Report/TitleView.swift
  CatchMe/CatchMe/Source/ViewControllers/CharacterVC.swift
  CatchMe/CatchMe/Source/ViewControllers/EditCatchuVC.swift
  CatchMe/CatchMe/Source/ViewControllers/ReportPopupVC.swift
  CatchMe/CatchMe/Source/ViewControllers/ReportVC.swift
  CatchMe/CatchMe/Source/ViewModels/CharacterViewModel.swift
  CatchMe/Podfile.lock
Labels: YoonAh-dev🌈, review required🍎

#172 Hotfix/168 main card align
  CatchMe/CatchMe/Source/ViewControllers/MainCardVC.swift
Labels: hotfix🔫, yangsubinn🐣

#174 [Fix] 메인뷰 로티 문제 수정(#173)
  CatchMe/CatchMe/Source/ViewControllers/MainVC.swift
Labels: bug, yangsubinn🐣
